export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
export const LOAD_FETCHED_PRODUCTS = 'LOAD_FETCHED_PRODUCTS';
export const ACTIVE_FILTER = 'ACTIVE_FILTER';
export const DEACTIVE_FILTER = 'DEACTIVE_FILTER';
export const TOOGLE_NAV = 'TOOGLE_NAV';
